name: Development Stats Box

on:
  schedule:
    - cron: "*/15 * * * *"
    
jobs:
  update-gist:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - name: Update gist
        uses: matchai/waka-box@master
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          GIST_ID: 008c174d6064d7f8265e04798933039d
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
